/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.datos.objetos.general;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Persona Value Object.
  * This class is value object representing database table PERSONA
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Persona implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_PERSONA;
    private int ID_TIPO_IDENTIFICACION;
    private double IDENTIFICACION;
    private double NOMBRES;
    private double APELLIDO1;
    private double APELLIDO2;
    private java.sql.Date FECHA_NACIMIENTO;
    private double TELEFONO;
    private double CELULAR;
    private double EMAIL;
    private int ANULADO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Persona () {

    }

    public Persona (int ID_PERSONAIn) {

          this.ID_PERSONA = ID_PERSONAIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_PERSONA() {
          return this.ID_PERSONA;
    }
    public void setID_PERSONA(int ID_PERSONAIn) {
          this.ID_PERSONA = ID_PERSONAIn;
    }

    public int getID_TIPO_IDENTIFICACION() {
          return this.ID_TIPO_IDENTIFICACION;
    }
    public void setID_TIPO_IDENTIFICACION(int ID_TIPO_IDENTIFICACIONIn) {
          this.ID_TIPO_IDENTIFICACION = ID_TIPO_IDENTIFICACIONIn;
    }

    public double getIDENTIFICACION() {
          return this.IDENTIFICACION;
    }
    public void setIDENTIFICACION(double IDENTIFICACIONIn) {
          this.IDENTIFICACION = IDENTIFICACIONIn;
    }

    public double getNOMBRES() {
          return this.NOMBRES;
    }
    public void setNOMBRES(double NOMBRESIn) {
          this.NOMBRES = NOMBRESIn;
    }

    public double getAPELLIDO1() {
          return this.APELLIDO1;
    }
    public void setAPELLIDO1(double APELLIDO1In) {
          this.APELLIDO1 = APELLIDO1In;
    }

    public double getAPELLIDO2() {
          return this.APELLIDO2;
    }
    public void setAPELLIDO2(double APELLIDO2In) {
          this.APELLIDO2 = APELLIDO2In;
    }

    public java.sql.Date getFECHA_NACIMIENTO() {
          return this.FECHA_NACIMIENTO;
    }
    public void setFECHA_NACIMIENTO(java.sql.Date FECHA_NACIMIENTOIn) {
          this.FECHA_NACIMIENTO = FECHA_NACIMIENTOIn;
    }

    public double getTELEFONO() {
          return this.TELEFONO;
    }
    public void setTELEFONO(double TELEFONOIn) {
          this.TELEFONO = TELEFONOIn;
    }

    public double getCELULAR() {
          return this.CELULAR;
    }
    public void setCELULAR(double CELULARIn) {
          this.CELULAR = CELULARIn;
    }

    public double getEMAIL() {
          return this.EMAIL;
    }
    public void setEMAIL(double EMAILIn) {
          this.EMAIL = EMAILIn;
    }

    public int getANULADO() {
          return this.ANULADO;
    }
    public void setANULADO(int ANULADOIn) {
          this.ANULADO = ANULADOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_PERSONAIn,
          int ID_TIPO_IDENTIFICACIONIn,
          double IDENTIFICACIONIn,
          double NOMBRESIn,
          double APELLIDO1In,
          double APELLIDO2In,
          java.sql.Date FECHA_NACIMIENTOIn,
          double TELEFONOIn,
          double CELULARIn,
          double EMAILIn,
          int ANULADOIn) {
          this.ID_PERSONA = ID_PERSONAIn;
          this.ID_TIPO_IDENTIFICACION = ID_TIPO_IDENTIFICACIONIn;
          this.IDENTIFICACION = IDENTIFICACIONIn;
          this.NOMBRES = NOMBRESIn;
          this.APELLIDO1 = APELLIDO1In;
          this.APELLIDO2 = APELLIDO2In;
          this.FECHA_NACIMIENTO = FECHA_NACIMIENTOIn;
          this.TELEFONO = TELEFONOIn;
          this.CELULAR = CELULARIn;
          this.EMAIL = EMAILIn;
          this.ANULADO = ANULADOIn;
    }


    /** 
     * hasEqualMapping-method will compare two Persona instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Persona valueObject) {

          if (valueObject.getID_PERSONA() != this.ID_PERSONA) {
                    return(false);
          }
          if (valueObject.getID_TIPO_IDENTIFICACION() != this.ID_TIPO_IDENTIFICACION) {
                    return(false);
          }
          if (valueObject.getIDENTIFICACION() != this.IDENTIFICACION) {
                    return(false);
          }
          if (valueObject.getNOMBRES() != this.NOMBRES) {
                    return(false);
          }
          if (valueObject.getAPELLIDO1() != this.APELLIDO1) {
                    return(false);
          }
          if (valueObject.getAPELLIDO2() != this.APELLIDO2) {
                    return(false);
          }
          if (this.FECHA_NACIMIENTO == null) {
                    if (valueObject.getFECHA_NACIMIENTO() != null)
                           return(false);
          } else if (!this.FECHA_NACIMIENTO.equals(valueObject.getFECHA_NACIMIENTO())) {
                    return(false);
          }
          if (valueObject.getTELEFONO() != this.TELEFONO) {
                    return(false);
          }
          if (valueObject.getCELULAR() != this.CELULAR) {
                    return(false);
          }
          if (valueObject.getEMAIL() != this.EMAIL) {
                    return(false);
          }
          if (valueObject.getANULADO() != this.ANULADO) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Persona, mapping to table PERSONA\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_PERSONA = " + this.ID_PERSONA + "\n"); 
        out.append("ID_TIPO_IDENTIFICACION = " + this.ID_TIPO_IDENTIFICACION + "\n"); 
        out.append("IDENTIFICACION = " + this.IDENTIFICACION + "\n"); 
        out.append("NOMBRES = " + this.NOMBRES + "\n"); 
        out.append("APELLIDO1 = " + this.APELLIDO1 + "\n"); 
        out.append("APELLIDO2 = " + this.APELLIDO2 + "\n"); 
        out.append("FECHA_NACIMIENTO = " + this.FECHA_NACIMIENTO + "\n"); 
        out.append("TELEFONO = " + this.TELEFONO + "\n"); 
        out.append("CELULAR = " + this.CELULAR + "\n"); 
        out.append("EMAIL = " + this.EMAIL + "\n"); 
        out.append("ANULADO = " + this.ANULADO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Persona cloned = new Persona();

        cloned.setID_PERSONA(this.ID_PERSONA); 
        cloned.setID_TIPO_IDENTIFICACION(this.ID_TIPO_IDENTIFICACION); 
        cloned.setIDENTIFICACION(this.IDENTIFICACION); 
        cloned.setNOMBRES(this.NOMBRES); 
        cloned.setAPELLIDO1(this.APELLIDO1); 
        cloned.setAPELLIDO2(this.APELLIDO2); 
        if (this.FECHA_NACIMIENTO != null)
             cloned.setFECHA_NACIMIENTO((java.sql.Date)this.FECHA_NACIMIENTO.clone()); 
        cloned.setTELEFONO(this.TELEFONO); 
        cloned.setCELULAR(this.CELULAR); 
        cloned.setEMAIL(this.EMAIL); 
        cloned.setANULADO(this.ANULADO); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
