/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.datos.objetos.ubicacion;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Departamento Value Object.
  * This class is value object representing database table DEPARTAMENTO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Departamento implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_DEPARTAMENTO;
    private String CODIGO_DANE;
    private String DEPARTAMENTO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Departamento () {

    }

    public Departamento (int ID_DEPARTAMENTOIn) {

          this.ID_DEPARTAMENTO = ID_DEPARTAMENTOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_DEPARTAMENTO() {
          return this.ID_DEPARTAMENTO;
    }
    public void setID_DEPARTAMENTO(int ID_DEPARTAMENTOIn) {
          this.ID_DEPARTAMENTO = ID_DEPARTAMENTOIn;
    }

    public String getCODIGO_DANE() {
          return this.CODIGO_DANE;
    }
    public void setCODIGO_DANE(String CODIGO_DANEIn) {
          this.CODIGO_DANE = CODIGO_DANEIn;
    }

    public String getDEPARTAMENTO() {
          return this.DEPARTAMENTO;
    }
    public void setDEPARTAMENTO(String DEPARTAMENTOIn) {
          this.DEPARTAMENTO = DEPARTAMENTOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_DEPARTAMENTOIn,
          String CODIGO_DANEIn,
          String DEPARTAMENTOIn) {
          this.ID_DEPARTAMENTO = ID_DEPARTAMENTOIn;
          this.CODIGO_DANE = CODIGO_DANEIn;
          this.DEPARTAMENTO = DEPARTAMENTOIn;
    }


    /** 
     * hasEqualMapping-method will compare two Departamento instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Departamento valueObject) {

          if (valueObject.getID_DEPARTAMENTO() != this.ID_DEPARTAMENTO) {
                    return(false);
          }
          if (this.CODIGO_DANE == null) {
                    if (valueObject.getCODIGO_DANE() != null)
                           return(false);
          } else if (!this.CODIGO_DANE.equals(valueObject.getCODIGO_DANE())) {
                    return(false);
          }
          if (this.DEPARTAMENTO == null) {
                    if (valueObject.getDEPARTAMENTO() != null)
                           return(false);
          } else if (!this.DEPARTAMENTO.equals(valueObject.getDEPARTAMENTO())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Departamento, mapping to table DEPARTAMENTO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_DEPARTAMENTO = " + this.ID_DEPARTAMENTO + "\n"); 
        out.append("CODIGO_DANE = " + this.CODIGO_DANE + "\n"); 
        out.append("DEPARTAMENTO = " + this.DEPARTAMENTO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Departamento cloned = new Departamento();

        cloned.setID_DEPARTAMENTO(this.ID_DEPARTAMENTO); 
        if (this.CODIGO_DANE != null)
             cloned.setCODIGO_DANE(new String(this.CODIGO_DANE)); 
        if (this.DEPARTAMENTO != null)
             cloned.setDEPARTAMENTO(new String(this.DEPARTAMENTO)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
