/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.datos.objetos.facturacion;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * CuentaCobro Value Object.
  * This class is value object representing database table CUENTA_COBRO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class CuentaCobro implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_CUENTA_COBRO;
    private int ID_FACTURA;
    private int ID_ESTADO;
    private String CCOBRO;
    private java.sql.Date FECHA_CRUCE;
    private java.sql.Date FECHA_PAGO;
    private int ANULADO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public CuentaCobro () {

    }

    public CuentaCobro (int ID_CUENTA_COBROIn) {

          this.ID_CUENTA_COBRO = ID_CUENTA_COBROIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_CUENTA_COBRO() {
          return this.ID_CUENTA_COBRO;
    }
    public void setID_CUENTA_COBRO(int ID_CUENTA_COBROIn) {
          this.ID_CUENTA_COBRO = ID_CUENTA_COBROIn;
    }

    public int getID_FACTURA() {
          return this.ID_FACTURA;
    }
    public void setID_FACTURA(int ID_FACTURAIn) {
          this.ID_FACTURA = ID_FACTURAIn;
    }

    public int getID_ESTADO() {
          return this.ID_ESTADO;
    }
    public void setID_ESTADO(int ID_ESTADOIn) {
          this.ID_ESTADO = ID_ESTADOIn;
    }

    public String getCCOBRO() {
          return this.CCOBRO;
    }
    public void setCCOBRO(String CCOBROIn) {
          this.CCOBRO = CCOBROIn;
    }

    public java.sql.Date getFECHA_CRUCE() {
          return this.FECHA_CRUCE;
    }
    public void setFECHA_CRUCE(java.sql.Date FECHA_CRUCEIn) {
          this.FECHA_CRUCE = FECHA_CRUCEIn;
    }

    public java.sql.Date getFECHA_PAGO() {
          return this.FECHA_PAGO;
    }
    public void setFECHA_PAGO(java.sql.Date FECHA_PAGOIn) {
          this.FECHA_PAGO = FECHA_PAGOIn;
    }

    public int getANULADO() {
          return this.ANULADO;
    }
    public void setANULADO(int ANULADOIn) {
          this.ANULADO = ANULADOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_CUENTA_COBROIn,
          int ID_FACTURAIn,
          int ID_ESTADOIn,
          String CCOBROIn,
          java.sql.Date FECHA_CRUCEIn,
          java.sql.Date FECHA_PAGOIn,
          int ANULADOIn) {
          this.ID_CUENTA_COBRO = ID_CUENTA_COBROIn;
          this.ID_FACTURA = ID_FACTURAIn;
          this.ID_ESTADO = ID_ESTADOIn;
          this.CCOBRO = CCOBROIn;
          this.FECHA_CRUCE = FECHA_CRUCEIn;
          this.FECHA_PAGO = FECHA_PAGOIn;
          this.ANULADO = ANULADOIn;
    }


    /** 
     * hasEqualMapping-method will compare two CuentaCobro instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(CuentaCobro valueObject) {

          if (valueObject.getID_CUENTA_COBRO() != this.ID_CUENTA_COBRO) {
                    return(false);
          }
          if (valueObject.getID_FACTURA() != this.ID_FACTURA) {
                    return(false);
          }
          if (valueObject.getID_ESTADO() != this.ID_ESTADO) {
                    return(false);
          }
          if (this.CCOBRO == null) {
                    if (valueObject.getCCOBRO() != null)
                           return(false);
          } else if (!this.CCOBRO.equals(valueObject.getCCOBRO())) {
                    return(false);
          }
          if (this.FECHA_CRUCE == null) {
                    if (valueObject.getFECHA_CRUCE() != null)
                           return(false);
          } else if (!this.FECHA_CRUCE.equals(valueObject.getFECHA_CRUCE())) {
                    return(false);
          }
          if (this.FECHA_PAGO == null) {
                    if (valueObject.getFECHA_PAGO() != null)
                           return(false);
          } else if (!this.FECHA_PAGO.equals(valueObject.getFECHA_PAGO())) {
                    return(false);
          }
          if (valueObject.getANULADO() != this.ANULADO) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass CuentaCobro, mapping to table CUENTA_COBRO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_CUENTA_COBRO = " + this.ID_CUENTA_COBRO + "\n"); 
        out.append("ID_FACTURA = " + this.ID_FACTURA + "\n"); 
        out.append("ID_ESTADO = " + this.ID_ESTADO + "\n"); 
        out.append("CCOBRO = " + this.CCOBRO + "\n"); 
        out.append("FECHA_CRUCE = " + this.FECHA_CRUCE + "\n"); 
        out.append("FECHA_PAGO = " + this.FECHA_PAGO + "\n"); 
        out.append("ANULADO = " + this.ANULADO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        CuentaCobro cloned = new CuentaCobro();

        cloned.setID_CUENTA_COBRO(this.ID_CUENTA_COBRO); 
        cloned.setID_FACTURA(this.ID_FACTURA); 
        cloned.setID_ESTADO(this.ID_ESTADO); 
        if (this.CCOBRO != null)
             cloned.setCCOBRO(new String(this.CCOBRO)); 
        if (this.FECHA_CRUCE != null)
             cloned.setFECHA_CRUCE((java.sql.Date)this.FECHA_CRUCE.clone()); 
        if (this.FECHA_PAGO != null)
             cloned.setFECHA_PAGO((java.sql.Date)this.FECHA_PAGO.clone()); 
        cloned.setANULADO(this.ANULADO); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
