/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo.datos.objetos.facturacion;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Descuento Value Object.
  * This class is value object representing database table DESCUENTO
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Descuento implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int ID_DESCUENTO;
    private int PORCENTAJE;
    private java.sql.Date FECHA_INICIO;
    private java.sql.Date FECHA_FIN;
    private int ANULADO;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Descuento () {

    }

    public Descuento (int ID_DESCUENTOIn) {

          this.ID_DESCUENTO = ID_DESCUENTOIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getID_DESCUENTO() {
          return this.ID_DESCUENTO;
    }
    public void setID_DESCUENTO(int ID_DESCUENTOIn) {
          this.ID_DESCUENTO = ID_DESCUENTOIn;
    }

    public int getPORCENTAJE() {
          return this.PORCENTAJE;
    }
    public void setPORCENTAJE(int PORCENTAJEIn) {
          this.PORCENTAJE = PORCENTAJEIn;
    }

    public java.sql.Date getFECHA_INICIO() {
          return this.FECHA_INICIO;
    }
    public void setFECHA_INICIO(java.sql.Date FECHA_INICIOIn) {
          this.FECHA_INICIO = FECHA_INICIOIn;
    }

    public java.sql.Date getFECHA_FIN() {
          return this.FECHA_FIN;
    }
    public void setFECHA_FIN(java.sql.Date FECHA_FINIn) {
          this.FECHA_FIN = FECHA_FINIn;
    }

    public int getANULADO() {
          return this.ANULADO;
    }
    public void setANULADO(int ANULADOIn) {
          this.ANULADO = ANULADOIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int ID_DESCUENTOIn,
          int PORCENTAJEIn,
          java.sql.Date FECHA_INICIOIn,
          java.sql.Date FECHA_FINIn,
          int ANULADOIn) {
          this.ID_DESCUENTO = ID_DESCUENTOIn;
          this.PORCENTAJE = PORCENTAJEIn;
          this.FECHA_INICIO = FECHA_INICIOIn;
          this.FECHA_FIN = FECHA_FINIn;
          this.ANULADO = ANULADOIn;
    }


    /** 
     * hasEqualMapping-method will compare two Descuento instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Descuento valueObject) {

          if (valueObject.getID_DESCUENTO() != this.ID_DESCUENTO) {
                    return(false);
          }
          if (valueObject.getPORCENTAJE() != this.PORCENTAJE) {
                    return(false);
          }
          if (this.FECHA_INICIO == null) {
                    if (valueObject.getFECHA_INICIO() != null)
                           return(false);
          } else if (!this.FECHA_INICIO.equals(valueObject.getFECHA_INICIO())) {
                    return(false);
          }
          if (this.FECHA_FIN == null) {
                    if (valueObject.getFECHA_FIN() != null)
                           return(false);
          } else if (!this.FECHA_FIN.equals(valueObject.getFECHA_FIN())) {
                    return(false);
          }
          if (valueObject.getANULADO() != this.ANULADO) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Descuento, mapping to table DESCUENTO\n");
        out.append("Persistent attributes: \n"); 
        out.append("ID_DESCUENTO = " + this.ID_DESCUENTO + "\n"); 
        out.append("PORCENTAJE = " + this.PORCENTAJE + "\n"); 
        out.append("FECHA_INICIO = " + this.FECHA_INICIO + "\n"); 
        out.append("FECHA_FIN = " + this.FECHA_FIN + "\n"); 
        out.append("ANULADO = " + this.ANULADO + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Descuento cloned = new Descuento();

        cloned.setID_DESCUENTO(this.ID_DESCUENTO); 
        cloned.setPORCENTAJE(this.PORCENTAJE); 
        if (this.FECHA_INICIO != null)
             cloned.setFECHA_INICIO((java.sql.Date)this.FECHA_INICIO.clone()); 
        if (this.FECHA_FIN != null)
             cloned.setFECHA_FIN((java.sql.Date)this.FECHA_FIN.clone()); 
        cloned.setANULADO(this.ANULADO); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
